name = "onboardy-analyzer"
workspace = "columbia-158966"
type = "agent"
public = false

[runtime]
timeout = 900
memory = 4096

[env]
IS_SANDBOX = "1"

[[triggers]]
  id = "trigger-analyze"
  type = "http"
[triggers.configuration]
  path = "agents/onboardy-analyzer/analyze"
  retry = 1

[[triggers]]
  id = "trigger-diagram"
  type = "http"
[triggers.configuration]
  path = "agents/onboardy-analyzer/diagram"
  retry = 1

[[triggers]]
  id = "trigger-chat"
  type = "http"
[triggers.configuration]
  path = "agents/onboardy-analyzer/chat"
  retry = 1

[[triggers]]
  id = "trigger-debug"
  type = "http"
[triggers.configuration]
  path = "agents/onboardy-analyzer/debug"
  retry = 0

[[triggers]]
  id = "trigger-debug-test"
  type = "http"
[triggers.configuration]
  path = "agents/onboardy-analyzer/debug/test"
  retry = 0
